services:
  graphdb:
    image: khaller/graphdb-free:${GDB_VERSION}
    command: ["--GDB_HEAP_SIZE", "${GDB_HEAP_SIZE}"]
    ports:
      - 127.0.0.1:7270:7200
    volumes:
      - "./config/config.ttl:/repository.init/sandbox/config.ttl:ro"
      
  blazegraph:
    image: lyrasis/blazegraph:${BG_VERSION}
    ports:
      - 127.0.0.1:8889:8080

  fuseki:
    image: secoresearch/fuseki:${FUSEKI_VERSION}
    ports:
      - 127.0.0.1:3030:3030
    environment:
      ADMIN_PASSWORD: admin
      ENABLE_DATA_WRITE: true
      ENABLE_UPDATE: true
      ENABLE_SHACL: true
      QUERY_TIMEOUT: 30000
